#!/usr/bin/env bash
set -euo pipefail

export CONCLAVE_CONTAINER_REGISTRY_URL=${CONCLAVE_CONTAINER_REGISTRY_URL:-"localhost:5000"}
export CONCLAVE_CONTAINER_REGISTRY_USERNAME=${CONCLAVE_CONTAINER_REGISTRY_USERNAME:-}
export CONCLAVE_CONTAINER_REGISTRY_PASSWORD=${CONCLAVE_CONTAINER_REGISTRY_PASSWORD:-}
export CONCLAVE_MAVEN_URL=${CONCLAVE_MAVEN_URL:-"https://software.r3.com/artifactory"}
export CONCLAVE_MAVEN_REPOSITORY=${CONCLAVE_MAVEN_REPOSITORY:-"sgxjvm-maven-nightly"}
export CONCLAVE_MAVEN_USERNAME=${CONCLAVE_MAVEN_USERNAME:-}
export CONCLAVE_MAVEN_PASSWORD=${CONCLAVE_MAVEN_PASSWORD:-}
